README.adoc
Just a small improvement: "GitHub" instead of "Github" 👍
=> Replace "Github" with "GitHub" in the `README` file

w02h01/test/pgdp/UnitTests.java
* Adds comments to existing tests a with intermediate steps (copied from the task)
* Adds `Assertions.assertEquals(1, PenguWarmup.penguEvolution(1, 0));` because 0 and 1 are always good to test
* Adds `Assertions.assertEquals(106, PenguWarmup.penguEvolution(70, 8));` to a multiple of 7 what is not 7.
* Adds `Assertions.assertEquals(17, PenguWarmup.penguEvolution(7, 10));` to ensure that the behavior of the task is correct implemented (source for this criteria): https://zulip.in.tum.de/#narrow/stream/1350-PGdP-W02H01/topic/Evolution.20der.20Penguine.20.7C.20Startwert.20ein.20Vielfaches.20von.20sieben/near/748278)
=> Improve tests for `PenguWarmup.checkPenguEvolutions`

w02h02/test/pgdp/CasinoTest.java
Adding a test that verifies that you display the lose message when the user has a net profit of 0 (e.g. first round winning 10 tokens, second round losing 10 tokens) because 0 is not "echter positiver Gewinn" (see task).
cc: @simonsmd
=> [W02H02] Add test for 0 net profit

w03h03/test/pgdp/MoreSeamCarvingTests.java
`toGradientMagnitude` does not have to be able to handle zero sized images. `shrink` on the other hand should return an empty array.
this addresses the issue we talked about in #29
=> Fix 0x6 gradientmagnitude

w04h03/test/pgdp.convexhull/ClosedConvexHullExample.java
Zulip > PGdP-W04H03 > Überflüssige Ecken
According to the Zulip post, this alternative test case is allowed, too.
=> [w04h03] added alternative accepted test case

w04h02/test/pgdp/megamerge/MegaMergeSortTest.java, w04h02/test/pgdp/megamerge/MergeRecursiveTest.java, w04h02/test/pgdp/megamerge/MergeTest.java, w04h02/test/pgdp/megamerge/UnitTests.java
The task description for the recursive `merge` method does not specify whether the merge steps as shown in the example must be _**contained**_ in the solution or if _**only**_ those merge steps are allowed. The current implementation of the test ignores all merge steps preceding the expected ones.
For the example array from Artemis `[[1], [2], [3], [4]]` the test allows both of the following variants because they both contain the merge steps from the example.
```
[[], [4], [4, 3], [4, 3, 2], [4, 3, 2, 1]]
[[4, 3], [4, 3, 2], [4, 3, 2, 1]]
```
=> [w04h02] more tests

w03h03/test/pgdp/SeamCarvingTest.java
feat(w03h03/test/pgdp/SeamCarvingTest.java): 
Hey, ich hab kurz an folgenden Corner Case gedacht: 
welcher Pixel ist aus der nächsten Zeile zu bevorzugen, wenn man sich gegenwärtig am ganz rechten Rand einer Zeile befindet und in der unteren Zeile die beiden rechtesten Zahlen gleich sind?
Z.B. hier, von der 10 in der ersten Zeile: soll die linke oder die rechte 5 gewählt werden?
| Rest von links  | Vorletzt | Letzt |
| ------------- | ------------- | - |
| ... | _ | 10 |
| ... | 5 | 5 |
Was hier passieren soll, wird mir aus der Aufgabe aber nicht ganz klar. Da steht ja, dass bei gleichen Zahlen "links" und "rechts" immer die linke gewählt werden soll, dagegen aber auch immer "die mittlere", wenn sie unter den niedrigsten ist... welche unter zwei Zahlen die mittlere ist, ist nicht ganz …
=> [W03H03] Add corner case test in build_seams_Seamsarray

w04h03/test/pgdp/UnitTest.java
Checks the combineHulls() method for correct handling of partially and completely empty or null input hulls.
Checks the quickHullLeftOf() method for correct handling of partially and completely invalid or null input points.
=> [W04H03] Null / empty / invalid inputs for combineHulls() and quickHullLeftOf()

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/validate_pr_title.yml
This PR adds a check to validate PR titles should start with [W00H00], e.g. [W03H03]. Contributors should use the name of the homework for which they made a change. If they haven't changed a homework (e.g. making changes to the pull request template in .github), they should use [*] as prefix (like in this PR).
The homework number must be H01, H02 or H03.
=> [*] Add check for pr title

w04h03/test/pgdp/UnitTest.java
The rewritten tests did not make use of `@ParameterizedTest` and therefore failed at the first assertion failure. This is suboptimal behavior because it causes actually passing tests to get swallowed as soon as one test fails.
There were tests that tried to define actually undefined behavior: https://zulip.in.tum.de/#narrow/stream/1451-PGdP-W04H03/topic/Parametervalidierung/near/788853
The `testEmptyHulls` test does not have to be passed but could held with some implementations. AEditet the test `DisplayName` accordingly. This should close #59
=> [W04H03] Rewrite PenguHull Tests

w04h02/test/pgdp/megamerge/MergeTest.java
Theoretically, is it not possible to hit these edge cases, when you call `megaMergeSort()`. However, we learned from W03 that this is nothing you can depend on. All methods are `protected` which means they can be called from outside the class. Therefore, it's possible to call the method with "stupid" input.
This PR contains this edge cases:
* .merge(int[][] arrays, int from, int to) should handle negativ from values
* .merge(int[][] arrays, int from, int to) should handle to values greater than the length of the arrays
* .merge(int[][] arrays, int from, int to) should handle a negative range
* .merge(int[][] arrays, int from, int to) should handle a range is out of bounds
* .merge(int[][] arrays, int from, int to) should handle a range where from is greater than to
Source for this …
=> [W04H02] Add test for edge cases of `.merge(int[][] arrays, int from, int to)`

w05h03/test/pgdp/messenger/test/ListBehaviourTest.java
This test can fail if the original list orderedList1 is edited during merge, which is allowed ("Was mit den Input-Listen passiert bleibt dir überlassen").
=> [W05H03] Update ListBehaviourTest.java

w06h01/test/pgdp/LoopTest.java
This test detects if loops are used in the source code because they are not allowed in W06H01. The implementation is very basic so it can contain false positive (using the word "for" or "while" in a comment or in a method name).
=> [W06H01] Add test for usage of loops

w06h01/test/pgdp/LoopTest.java
Using regular expression instead of a simple keyword search (suggested by @julian-hartl in https://github.com/MaximilianAnzinger/pgdp2223-tests/pull/114/files#r1035113758).
=> [W06H01] Use RegExp instead of simple keyword search for `testUsageOfLoops`

w06h02/test/pgdp/ds/MultiStackTest.java
The task description does not specify whether or not the mem array must get modified by `pop()` ([confirmed](https://zulip.in.tum.de/#narrow/stream/1480-PGdP-W06H02/topic/pop.28.29.20muss.20mem.20ver.C3.A4ndert.20werden.3F)).
This pr removes/fixes tests which assume that unused memory has to be filled with zeros. Closes #119 and closes #125
=> [W06H02] remove/fix tests expecting specific values in unused mem array

w06h03/test/pgdp/ds/DenseGraphCapabilityTest.java, w06h03/test/pgdp/ds/SparseGraphCapabilityTest.java
The task description does not specify a specific order. Therefore expected and actual have to be sorted before comparison.
Working with `Set<Integer>` would be wrong because it would Eliminate illegal duplicates.
Fixes #124.
=> [W06H03] compare sorted list of adjacent nodes

w07h02/test/pgdp/security/test/UnitTests.java
`"end"` is not a valid depiction for the final state... It is supposed to be `"yellow"`, `"green/yellow/red/blue"`  or `"chequered"` respectively.
=> [W07H02] fix invalid depiction of final state

w07h02/test/pgdp/security/TestBase.java, w07h02/test/pgdp/security/TrackTest.java
* The behavior for tracks with size < 4 is not specified when creating/removing a lapped car. Therefore there shouldn't be any tests for this case. We can assume that the track size is always >= 4 if there are lapped cars involved ([confirmed](https://zulip.in.tum.de/#narrow/stream/1494-PGdP-W07H02/topic/Track.20L.C3.A4nge/near/832611)).
* The behavior of `up()`/`down()` for input `null` is not defined. We therefore shouldn't test. Input is guaranteed to be a valid String ([confirmed](https://zulip.in.tum.de/#narrow/stream/1494-PGdP-W07H02/topic/up.2Fdown.20type.20.3D.3D.20null/near/836835)).
=> [W07H02] remove tests that are trying to define undefined behaviour

w07h03/test/pgdp/sim/SimulationTest.java
* we can not use getters which aren't mandatory according to the task description, therefore we have to use reflection
* uninitialized `SimConfig` values could lead to confusing errors with faulty implmentations
=> [W07H03] access cells array via reflection and initialize SimConfig

w08h03/test/pgdp/datastructures/UnitTest.java
With this tree the node 13 returns `[null, 14, null, 15]` when calling `getChildren()`. My first implementation passed all other tests but failed this one. Therefore, I'm adding it to our tests.
=> [W08H03] Add a test with a tree where a node returns `[null, a, null,  b]` for `getChildren()`

w08h03/test/pgdp/datastructures/RandomTest.java
`expected` and `actual` were reversed:
`expected` should be on the left side and actual on the right side.
I have also renamed `solution` to `expected` for a more consistent naming 👍
=> [W08H03] Fix order to expected and actual

w08h01/test/pgdp/NoUsageOfValuesMethodTest.java, w08h03/test/pgdp/datastructures/PerformanceTest.java, w08h03/test/pgdp/datastructures/UnitTest.java
This adds 2 tests. Both create trees with 1 million nodes.
The first test then iterates through all of them again, times it, and checks the output for correctness.
Additionally, it prints RAM usage during some steps of the way but includes a disclaimer that this isn't a terribly useful number.
The second test iterates through only the first 1k elements, times it, and checks the output for correctness.
The latter will perform much better with lazy solutions.
I also removed a commented-out code block.
🐧
=> [W08H03] Add performance tests

w08h02/test/pgdp/pools/TaskBehaviorTest.java, w08h02/test/pgdp/pools/TaskFunctionBehaviorTest.java
> Überschriebene Methoden hashCode und equals, die jeweils nur von ID abhängig sein sollen.
The goal of the first test is to see if TaskFunction::equals uses a Class::getClass comparison thus locking Class::equals to instances of the same class. TaskFunction::equals may only be dependent on ID, in case of altering a different instance of TaskFunction to the same value (e.g. by a method overwrite) it should yield true.
The second test is trivial as we are not overwriting any methods in the subclass, we could still produce an undefined behaviour in flawed implementations that can't handle subclasses.
=> [W08H02] test(TaskFunctionBehaviorTest): Add strict equals comparison

w09h01/test/pgdp/pingutrip/ReadWayPointsTest.java
Using `assertArrayEquals` is much better.
=> [W09H01] Use `assertArrayEquals` (refactoring)

w09h01/test/pgdp/pingutrip/ReadWayPointsTest.java
When passing an empty String, Java throws an `IOException`. However, this is not covered by the Artemis tests is not required to get the points. Because this led to problems (see #192), I'm going to change it to a path that is not existing.
=> [W09H01] Do not use an empty string for file path for the `readWayPoints` method test

w09h02/test/pgdp/trains/processing/AverageDelayByHourTest.java, w09h02/test/pgdp/trains/processing/OfficialExampleTests.java
* Moves the example test from `OfficialExampleTests.java` into a separate file `AverageDelayByHourTest.java`
* Add test when list of train connections is empty
=> [W09H02] Add tests for `averageDelayByHour`

w09h02/test/pgdp/trains/processing/DelayComparedToTravelTimeTest.java
* Adds a test where the list of train connections is empty
* Adds a test where a train is too early => this should not change the amount of delay
=> [W09H02] Add more tests for `delayComparedToTravelTimeTest`

w09h02/test/pgdp/trains/processing/AverageDelayAtTest.java, w09h02/test/pgdp/trains/processing/OfficialExampleTests.java
* Moves the example test from `OfficialExampleTests.java` into a separate file `AverageDelayAtTest.java`
* Add test when list of train connections is empty
* Add test when the provided train stop is not included in the list of train connections
=> [W09H02] Add tests for `averageDelayAt`

w09h02/test/pgdp/trains/processing/OfficialExampleTests.java, w09h02/test/pgdp/trains/processing/WorstDelayedTrainTest.java
* Moves the example test from `OfficialExampleTests.java` into a separate file `WorstDelayedTrainTest.java`
* Adds a test when the stream of connections is empty => should return `null`
* Adds a test when there are multiple connections with same worst delay => return any of the worst delayed connections
* Adds a test when there are no delayed connections => return any of the connections
=> [W09H02] Add tests for `worstDelayedTrain`

w09h02/test/pgdp/trains/processing/DelayComparedToTravelTimeTest.java
=> [W09H01] Add comment for explaining the `testTooEarlyTrainsShouldNotCompensateTheDelay` comment

w10h03/test/pgdp/infinite/InfiniteTreeTest.java, w10h03/test/pgdp/infinite/Lambdas.java, w10h03/test/pgdp/infinite/Trees.java
It was not clear to me what `depthTest` actually does. I expected it to test if the implementation complies with the specified search depth which was not the case.
@Anatoly03 hope you're okay with this replacement.
=> [W10H03] replace depthTest with findTest

w11h03/test/pgdp/networking/HTTPTest.java, w11h03/test/pgdp/networking/SocketTest.java
This pull-request fixes the following issues:
- `getContacts()` not being allowed to return an empty map
- `testMessageHuge()` output being different on Windows
- `testMessage()` not accepting an arbitrarily long message buffer
- Not providing reasons for many assertions (Added Zulip links)
=> [W11H03] Fix many issues in W11H03

w11b01/test/pgdp/pengusurvivors/ResidualGraphTest.java
Having different flow rates in a graph like `a -> b -> c` leads to miscalculated maximum flow because it is an invalid state.
An error of this nature lead to the calculated (and expected) flowrate being 8 instead of 6.
=> [W11B01] fix getmaxFlow
