w02h03/test/pgdp/UnitTests.java
A TC generator for the w02h03 homework. It only compares the resulting value. I did not manage to get it working without a delta value in the comparison. Due to the issue that the returned double of Math.sqrt is sometimes slightly imprecise. Which wouldn't be a problem if we round the value. But because it is stated that the resulting value should be cut off and not rounded... -> That's a problem.
=> TC gen for w02h03

w02h01/test/pgdp/UnitTests.java
Test to check for overflow mistakes in penguPowers.
=> test against overflow in checkPenguPowers

w02h03/test/pgdp/UnitTests.java
I added special TCs which will be tested in my TC generator. As I stated earlier because of the delta value in the TC generator, results which are wrong by 0.1 will be tested correct, even if they shouldn't. Because of that it is necessary to add at least a few manual test to overcome this problem. The tests are also somewhat special. Why? That's for you to find out :)
=> Add special TC for w02h03

w02h01/test/pgdp/UnitTests.java
A test to check the implementation of `PenguWarmup.penguInfoOut`. Checks if the output to the console is correct.
=> Add test for `PenguWarmup.penguInfoOut`

w02h03/test/pgdp/UnitTest2.java
The class name did not match the file name and package was not set. Furthermore I removed the public keywords in front of tests like Dustin suggested. And there was one unused value which I removed.
=> Doing the Dustin things. Cleanup and stuff

w02h01/test/pgdp/UnitTests.java, w02h03/test/pgdp/UnitTests.java
This tests the output of sqrt(1049.76) against the expected output example.
Feel free to find a cleaner solution :)
=> add test for output format of sqrt() method and modularize test to avoid confusion

w02h02/test/pgdp/CasinoTest.java, w02h02/test/pgdp/LineInputStream.java
These unit tests simulate user input and check if the correct output is produced. The seed for the RNG is set using reflection.
Currently the tests check
- the example provided in the assignment on Artemis
- the handling of invalid input
- the message if the player makes a profit
- if the game ends if the player has no tokens left
=> Tests for w02h02

w03h01/test/pgdp/UnitTests.java
Tests für die Hausaufgabe W03H01
=> Added unit tests for W03H01

README.adoc
=> syslink to symlink

w03h01/test/pgdp/FilterTest.java, w03h01/test/pgdp/QuantitiesTest.java, w03h01/test/pgdp/RotateTest.java, w03h01/test/pgdp/SumOfSquaresTest.java, w03h01/test/pgdp/ZipManyTest.java, w03h01/test/pgdp/ZipTest.java
The tests in this PR should include all tests from #19 (although the tests are not identical) and some more edge cases (e.g. larger overflows in sumOfSquares). The tests are also split into multiple classes and use parameterized tests which makes the output of test results more organized and makes it easier to see which tests (and inputs) failed.
Tests included in this PR:
- sumOfSquares
- Correct result for multiple inputs (positive, negative, long limit, ...)
- Handling of different overflows
- Empty array
- zip/zipMany
- Examples from Artemis
- Arrays of different lengths
- Empty arrays
- Arrays with identical elements (added from #19)
- filter
- Correct filtering for multiple inputs (positive, negative, equal min/max, integer limits, ...)
- Min larger than max
- Empty array
- rotate
- …
=> w03h01: add tests

w03h01/test/pgdp/ZipManyTest.java
Add testcase for error reported by student that doesn't result in a test failure
=> Add testcase

README.adoc
Just a fix for the the link cmd
=> Fix link instructions

w03h03/test/pgdp/MoreSeamCarvingTests.java
added own tests for every method (some more extensive than others, due to the increase in difficulty to manually check the later methods). Note that the test toGradientMagnitude5x6Image() has not been manually checked, but worked with my implementation. Currently, see it more as a way to check whether you changing something inside toGradientMagnitude() still gives the same output.
=> added own tests for SeamCarving

.github/PULL_REQUEST_TEMPLATE.md
=> Add note for adding the week and the number of the homework as prefix in the PR title

w03h01/test/pgdp/RotateTest.java
add tests with `Integer.MAX_VALUE` and `Integer.MIN_VALUE` as rotation amount
=> [W03H01] add tests with max value as rotation amount

w03h03/test/pgdp/SeamCarvingTest.java
this should fix #30
please let someone review my changes before merging
=> Fix segfault macos arm

w03h03/test/pgdp/SeamCarvingTest.java
someone reversed expected and actual values...
=> fix mixed up expected and actual values

w04h02/test/pgdp/UnitTests.java
The order of parameters in the error message was wrong resulting in the wrong error message when testing.
=> [W04H02] Fixed order of parameters

w04h01/test/pgdp/RecursivePingulogyTest.java
Covers an untested edgecase in which p0, p1 and p2 are equal to 0.
=> [W04H01] Add new edgecase test

.gitignore
Added macOS' .DS_Store file to .gitignore
=> Added macOS .DS_Store file to .gitignore

.github/PULL_REQUEST_TEMPLATE.md
=> Add note for splitting a pull request if it changes multiple tasks

w04h02/test/pgdp/megamerge/UnitTests.java
protected methods in `MegaMergeSort.java` were not accessible -> moved Test into same package to fix this
=> move test into package megamerge

w04h02/test/pgdp/megamerge/MergeRecursiveTest.java
=> [W04H02] fix mergeorder test

w04h03/test/pgdp/ConvexHullTests.java
Laut Tutor in ZÜ2 (Mi 16:00) verrät keine Lösung
Tests überprüfen einfache Funktionen in W4H03
=> [W04H03] Added Tests for Convexhulls

w04h02/test/pgdp/megamerge/MergeRecursiveTest.java
W04H02 Problem bei Merge Array Test wo input1 und input2 manchmal von users geändert werden, sodass der nächste funktionsaufruf schief läuft.
=> [W04H02] Changed input1 and input2 to newly defined arrays so overwrite doesn't happen

w04h02/test/pgdp/megamerge/MergeRecursiveTest.java, w04h02/test/pgdp/megamerge/UnitTests.java
These methods, variables and imports are not used. Unused code should not be committed.
=> [W04H02] Remove unused imports, variables and methods

w04h01/test/pgdp/RecursivePingulogyTest.java
This test covers `pinguDNA(...)` when one or both of the parameters are at their highest possible value (`Integer.MAX_VALUE`).
=> [W04H01] Add test with Integer.MAX_VALUE for pinguDNA

w04h03/test/pgdp/AdditionalQuickHullTests.java
=> [W04H03] Added more quickhull tests

w05h02/test/pgdp/pingunetwork/structural/GroupStructuralTest.java, w05h02/test/pgdp/pingunetwork/structural/InteractionStructuralTest.java, w05h02/test/pgdp/pingunetwork/structural/PictureStructuralTest.java, w05h02/test/pgdp/pingunetwork/structural/StructuralTest.java, w05h02/test/pgdp/pingunetwork/structural/UserStructuralTest.java
Dieses PR fügt Structural Tests für die zu erstellenden Attribute, Konstruktoren und Methoden hinzu. Es wird nur getestet, ob alle notwendigen Elemente (Attribute, Konstruktoren, Methoden) existieren. Zudem wird getestet, ob im Falle von Konstruktoren auch die Reihenfolge der Parameter passt.
=> [W05H02] Added structural tests

w05h03/MessengerTests.java, w05h03/test/pgdp/MessengerTests.java
nach meinem Verständnis testet das einige Edge-cases / Sonderfälle und verrät keine Lösung
=> [W05H03] Added Tests for w05h03 Messenger

w05h02/test/pgdp/BehaviorTest.java, w05h03/test/pgdp/messenger/test/ListBehaviourTest.java, w05h03/test/pgdp/messenger/test/PinguTalkBehaviourTest.java, w05h03/test/pgdp/messenger/test/UserArrayBehaviourTest.java
Testing initial creation of instances and the basic behaviour.
Testing user methods that we are suppose to implement.
Testing group methods that we are suppose to implement.
=> [W05H02] Added behaviour tests for the second task

w05h02/test/pgdp/pingunetwork/behavioral/PinguNetworkTest.java, w05h03/test/pgdp/MessengerTests.java, w05h03/test/pgdp/ModifierTests.java, w05h03/test/pgdp/ReflectionHelper.java
=> [W05H03] Added structural tests and rewrote MessengerTests using reflection

w05h03/test/pgdp/ListMergeTests.java
Tests behaviour of `pgdp.messenger.List.megaMerge`
=> [W05H03] tests for list merging

w05h03/test/pgdp.messenger.behavior/ListTest.java, w05h03/test/pgdp.messenger.behavior/PinguTalkTest.java
Chang the import paths for the TestUtils imports
=> [W05H03] change the import paths for the TestUtils

w05h02/test/pgdp/pingunetwork/behavioral/PinguNetworkTest.java
Changed the package and added an import for all the classes in package pgdp.pingunetwork
=> [W05H02] changed the package and import from package pgdp.pingunetwork

w05h02/test/pgdp/pingunetwork/structural/InteractionStructuralTest.java
=> [W05H02] Fix InteractionStructuralTest

w05h03/test/pgdp/messenger/test/PinguTalkBehaviourTest.java
This class is not used and unused code should not be committed.
cc: @tdphucvn
=> [W05H03] Remove empty class `PinguTalkBehaviourTest.java`

w05h03/test/pgdp/MessengerTests.java, w05h03/test/pgdp/messenger/test/UserArrayBehaviourTest.java
Under https://zulip.in.tum.de/#narrow/stream/1467-PGdP-W05H03/topic/UserArray.20addUser you can find the answer that these test cases are not tested. Not tested test case should not be committed.
cc: @tdphucvn
Closes #92
=> [W05H03] Remove optional tests

w06h01/test/pgdp/KinguinTest.java, w06h01/test/pgdp/ReverseTest.java, w06h01/test/pgdp/TestAPI.java, w06h01/test/pgdp/ThreshTest.java, w06h01/test/pgdp/ZipTest.java
Wir muessen uns irgendwie einigen wie wir perfomance testen, und die tests fuer thresh funktionieren nicht ganz.
=> [W06H01] Add tests for all methods of week 6 h 1

w06h02/test/pgdp/ds/MultiStackTest.java, w06h02/test/pgdp/ds/RingBufferTest.java
Added basic unit test, that check the desired behavior for simple examples. Tests for edge cases will be added later.
=> [W06H02] Add basic unit tests

w06h03/test/pgdp/ds/behavior/DenseGraphTest.java, w06h03/test/pgdp/ds/behavior/GraphTest.java, w06h03/test/pgdp/ds/behavior/SparseGraphTest.java
Added tests that test the basic functionality of both the SparseGraph and DenseGraph.
=> [W06H03] Add unit tests

w06h02/test/pgdp/ds/MultiStackTest.java
include value checks for return of empty stack tests
=> [W06H02] [MINOR] add tests for empty stack

w06h03/DeGraphViz.java
Added DeGraphViz.java, a method that allows for easy reconstruction of a graph, given the instruction set from the graph visualization website.
Allows for easy conversion of graphViz instructions to actual instructions executed on the given graph.
Does not do a lot of error detection, meaning the graphViz instructions should first be checked for correctness
on the graphViz website.
How to use this method:
1. Initialize a new graph (sparse or dense) with the correct number of nodes.
2. Create a new String object by first typing the double quotes (""), then pasting the instructions from the website between them (line breaks should be converted to \n).
3. Alternatively: Create a new String object using 6 double quotes ("""""") (called a text block), then pasting the instructions in between …
=> [W06H03] added method to easily reconstruct graph given instruction set

w06h02/test/pgdp/ds/MultiStackTest.java, w06h02/test/pgdp/ds/RingBufferTest.java
Added some more tests:
- Integer.MIN_VALUE should be returned when empty stack is popped (same for top())
- The head stack should never be changed
- Appended stacks should have double capacity (now tested up to 10 newly created stacks)
- Top() should only return the value at the top and not remove it
=> [W06H02] Add further tests

w06h03/test/pgdp/ds/DenseGraphCapabilityTest.java, w06h03/test/pgdp/ds/SparseGraphCapabilityTest.java, w06h03/test/pgdp/ds/behavior/GraphTest.java
* add missing package declaration
* sort array returned by `getAdj()` before checking for equality
=> [W06H03] fix

w06h02/test/pgdp/ds/MultiStackTest.java
=> [W06H02] Added tests for returned values

w06h03/test/pgdp/ds/behavior/DenseGraphTest.java, w06h03/test/pgdp/ds/behavior/GraphTest.java, w06h03/test/pgdp/ds/behavior/SparseGraphTest.java
The new tests cover the following:
- Negative amount of nodes (is possible)
- Out of range calls on isAdj, getAdj and addEdge
- Removal of isAdjFast test
=> [W06H03] Add further tests

w06h01/test/pgdp/ReverseTest.java, w06h01/test/pgdp/TestBase.java, w06h01/test/pgdp/ZipTest.java
This change adds checks for the reverse() and zip(.., ..) tests to look out for any RecIntListElement creation and modification inside the test subject.
=> [W06H01] Added checks for illegal modification and creation of RecIntListElements

w06h03/test/pgdp/ds/behavior/GraphTest.java
getAdj: When the id is out of range getAdj should return null
=> [W06H03] getAdj: when index is out of range return null

w06h01/test/pgdp/LoopTest.java
* walk all .java files in src directory
* output line number of offending keyword
=> [W06H01] improve loop finding

w06h01/test/pgdp/ReverseTest.java, w06h02/test/pgdp/ds/MultiStackTest.java
=> [W06H01] Added two more tests for reverse

w06h02/test/pgdp/ds/MultiStackTest.java
Just realized I had a bug in my code, that has not been tested for yet. I can't say which bug specifically as this would reveal too much about my implementation, but I can say that this test covers it.
=> [W06H02] Add check for illegal stack creation

w06h01/test/pgdp/KinguinSortTest.java
Es wurde ein Check für gleiche Elements und eins für korrekte Links (next/prev) hinzugefügt.
=> [W06H01] check for equals elements and correclty setted links

w06h02/test/pgdp/ds/MultiStackTest.java
Minimale Änderung, aber wichtiger EdgeCase
=> [W06H02] Test for EdgeCase: top when MultiStack is Empty

w07h02/test/pgdp/mocks/MethodCall.java, w07h02/test/pgdp/mocks/Mock.java, w07h02/test/pgdp/mocks/SignalPostMock.java, w07h02/test/pgdp/security/FinishPostTest.java, w07h02/test/pgdp/security/FlagPostTest.java, w07h02/test/pgdp/security/LightPanelTest.java, w07h02/test/pgdp/security/SignalPostTest.java, w07h02/test/pgdp/security/TestBase.java, w07h02/test/pgdp/security/TrackTest.java
Added tests for each subtask.
Not sure if the test for "printStatus" in the Track class is correct, because I don't seem to pass the public test on artemis.
=> [W07H02] Add tests

w07h02/test/pgdp/security/test/UnitTests.java
Unit Tests for the LightPanel, FlagPost and FinishPost and basic behavior. Feel free to simplify the structure of the tests.
=> [W07H02] Unit tests for the LigthPanel, FlagPost and FinishPost

README.adoc
Closes #140.
In the past there have been still a lot of specific questions on how to get the tests to run... This should clear up some of them.
=> [*] update usage to be hopefully more helpful

w07h03/pgdp/sim/FieldVisualizeHelper.java, w07h03/pgdp/sim/SimulationTest.java
Includes #131 
An easy way to test the whole simulation, just define the seed, height, width and expected states. Example:
```
@Test
@DisplayName("One single plant only")
void singlePlant() {
var states = new String[]{"""
p . . . .
. . . . .
. . . . .
. . . . .
. . . . .""", """
p . . . .
w . . . .
. . . . .
. . . . .
. . . . .""", """
p w . . .
w . . . .
. . . . .
. . . . .
. . . . .""", """
p w w . .
w w . . .
w . . . .
. . . . .
. . . . .""", """
p w w w .
w w w . .
w w . . .
. w . . .
. . . . ."""};
runTest("plant", 5, 5, states);
}
```
=> [W07H03] Template for simulation tests and four tests

w07h02/test/pgdp/security/TrackTest.java
=> [W07H02] replace line separators for better compatibility

w07h03/test/pgdp/sim/EatBehaviourTest.java
=> [W07H03] fix(eatBehaviour): insert eating party at x y

w07h03/test/pgdp/sim/RandomGeneratorTest.java
As mentioned in the problem statement, the RandomGenerator can only be used in certain places. Therefore, I create a test to check if it has been misused.
=> [W07H03] test for the use of RandomGenerator

w07h03/test/pgdp/sim/SimulationTest.java
Essentially checked that the both wolfs will die within spec. For this reason, the existing `hamsterEatsPlantWolfEatsHamster` was extended to include extinction.
=> [W07H03] extended hamster,wolf test with death

w08h03/test/pgdp/datastructures/UnitTest.java
add empty test
add artemis tests
ich hoffe ich benutzte git diesmal richtig 🥲
=> [W08H03] add first tests

w08h01/test/pgdp/SimpleGenericsTest.java
Die Tests haben teilweise falsche Comparator als Parameter übergeben, ich hab das gefixt und die Standard Java Implementierung verwendet.
=> [W08H01] Fixed comparator

w08h02/test/pgdp/pools/TaskBehaviorTest.java, w08h02/test/pgdp/pools/TaskFactoryBehaviorTest.java, w08h02/test/pgdp/pools/TaskFunctionBehaviorTest.java, w08h02/test/pgdp/pools/TaskPoolBehaviorTest.java, w08h02/test/pgdp/pools/structural/StructuralTest.java, w08h02/test/pgdp/pools/structural/TaskFactoryTest.java, w08h02/test/pgdp/pools/structural/TaskFunctionStructuralTest.java, w08h02/test/pgdp/pools/structural/TaskPoolStructuralTest.java, w08h02/test/pgdp/pools/structural/TaskStructuralTest.java
Added structural behavioral tests which include the Artemis tests and examples aswell as own edge cases
=> [W08H02] added behavioral and structural tests

w08h03/test/pgdp/datastructures/UnitTest.java
this pr introduces generic & generative tests for hard
=> [W08H03] add generic and dynamic tests

w08h03/test/pgdp/datastructures/UnitTest.java
Test behaviour for two iterators iterating over the same Tree simultaneously.
=> [W08H03] test parallel iterators

w08h03/test/pgdp/datastructures/RandomTest.java
Vielleicht etwas viele überflüssige Tests, aber better be safe than sorry. Vergleicht die Rückgabe des Iterators mit einer von Collections.sort() sortierten ArrayList. Laut zulip entspricht das immer der korrekten Reihenfolge (https://zulip.in.tum.de/#narrow/stream/1499-PGdP-W08H03/topic/Baum.20Sortierung/near/852670).
=> [W08H03] Use brute force to find possible edge cases

w08h01/test/pgdp/SimpleGenericsTest.java
i added for the exercise intersection the test if one Collection out of the array is empty the return collection is also empty
=> [W08H01] adding the test if one collection out of the array is empty

w08h03/test/pgdp/datastructures/RandomTest.java
`Collections.sort` is getting called unnecessarily. This PR fixes the unnecessary call and improves the performance of the tests.
=> [W08H03] Fixed performance

w08h03/test/pgdp/datastructures/UnitTest.java
edits: made parallelIteratorsTest seeded, asserted NoSuchElementException return message
=> [W08H03] Added big tree test and edited existing tests

w08h03/test/pgdp/datastructures/UnitTest.java
Multiple iterator support (added in #168) is not necessary:
https://zulip.in.tum.de/#narrow/stream/1499-PGdP-W08H03/topic/mehrere.20iteratoren
=> [W08H03] revert test parallel iterators

w08h01/test/pgdp/SimpleGenericsTest.java, w08h02/test/pgdp/pools/TaskPoolBehaviorTest.java
The Change is in the Test for TaskPool and checks if equales work right it is simply the test from artemis but for the sake of completeness i would add them here to
=> [W08H02] Adds a Test if epuals works correctly

w09h01/test/pgdp/pingutrip/ReadWayPointsTest.java
Two simple tests for `readyWayPoints`. When you pass these two tests you should also pass the Artemis tests.
=> [W09H01] Add tests for `readWayPoints`

.github/workflows/validate_pr_title.yml
Closes #186
cc: @HendrikHuebner
=> [*] Fix `validate-pr-title` GitHub Action for bonus tasks

w09h01/test/pgdp/pingutrip/LegalCheck.java
tests wether homework uses illegal imperative java statements such as loops and conditions
=> [W09H01] Legality of Homework Checker

w08h03/test/pgdp/datastructures/RecursiveTest.java
This test checks if the returned iterator calls any recursive method provided by `QuarternarySearchTree` or `QuarternaryNode`
=> [W08H03] add test for recursion

.gitignore
Moving https://github.com/hmelder/pgdp2223-tests/commit/18273adb6f53723196e05963d3be243dc26ebd2c (commit of #193) into a separate PR.
=> [*] Add temporary files for vim (`.swp`) and (`.swo`) to `.gitignore`

w09b01/pgdp/SimpleAITest.java
Ein paar Tests für SimpleAI in W09B01
=> [W09B01] SimpleAITest

w09h02/test/pgdp/trains/processing/OfficialExampleTests.java
Diese Tests sind eine 1 zu 1 Umwandlung der offiziellen Beispiele in der main method (W09H02). Das alles aber mit debugger und Konsole zu testen ist sehr umständlich. Daher die Tests. Mit diesen Tests passe ich alle tests auf Artemis, kann aber natürlich nicht garantieren, dass alle Tests korrekt sind.
=> [W09H02] Converted all official Examples from the main method to JUnit Tests

w09b01/pgdp/AITests.java, w09b01/pgdp/GameTests.java, w09h03/test/pgdp/filter/DGTest.java
=> [W09H03] Added Some Tests for VideoContainer (Konstruktor, Limit) and for Operations (GrayScale, Crop, Encode, Decode)

w09h01/test/pgdp/pingutrip/OnWayTest.java
Add two tests:
* Point is on the way
* Point is not on the way
=> [W09H01] Add tests for `PinguTrip.onTheWay` (task 6)

w09h03/test/pgdp/filter/DGTest.java, w09h03/test/pgdp/filter/DecodedTextFromVideo.java
* fix potential bug (unnecessarily instantiating `VideoContainer` could lead to one frame getting skipped)
* rearrange debug output and assertions (debug output would not get saved on failure)
* general cleanup
=> [W09H03] cleanup DGTest tests

w09h01/test/pgdp/pingutrip/PrettyDirectionsTest.java, w09h01/test/pgdp/pingutrip/ReadWayPointsTest.java
* add missing import
* better cross platform support (replace `'\n'` with `System.lineSeparator()`)
=> [W09H01] fix missing import & better cross platform compatibility

w09h01/test/pgdp/pingutrip/LegalCheckTest.java
Our `CONTRIBUTING.md` says that test files should end with `...Test.java`. Therefore, I changed the `LegalCheck.java` to `LegalCheckTest.java`
=> [W09H01] Rename `LegalCheck` to `LegalCheckTest`

w10h03/test/pgdp/infinite/InfiniteNodeTest.java, w10h03/test/pgdp/infinite/InfiniteTreeTest.java, w10h03/test/pgdp/infinite/Lambdas.java, w10h03/test/pgdp/infinite/OptimizableComparable.java, w10h03/test/pgdp/infinite/Trees.java
Unit Tests for [Bis zur Unendlichkeit](https://artemis.in.tum.de/courses/201/exercises/8842)
- add: `InfiniteNodeTest.java` and `InfiniteTreeTest.java` to test basic behaviour of homework methods.
- add: `OptimizableComparable.java` Implementation of `Optimizable` Instance. !!! This is not part of the homework, this why it can be implemented in the test repository. !!!
- add: `Lambdas.java` and `Trees.java` to provide some default static methods for the tests and architecture future test code
=> [W10H03] Implement first tests

w10h02/test/pgdp/teams/ArtemisTest.java, w10h02/test/pgdp/teams/Lib.java, w10h02/test/pgdp/teams/UnitTest.java
Tests for [W10H02](https://artemis.in.tum.de/courses/201/exercises/8841)
- `ArtemisTest.java` Tests following Artemis Examples
- `Lib.java` Reflections for getting private fields and static penguins.
- `UnitTest.java` Tests not from Artemis using extra special pingus.
If you want to add yourself as a penguin do it in `Lib.java`
=> [W10H02] First Commit

w10h02/test/pgdp/teams/ArtemisTest.java
As fellow students pointed out (thanks to Hanne H.) this test contained leftover code. This PR gets rid of it.
=> [W10H02] Hot Fix: Delete Leftover Code

w10h02/test/pgdp/teams/Lib.java, w10h02/test/pgdp/teams/UnitTest.java
Some implementations of `computeScores()` may run into an overflow in this test.
=> [W10H02] Added computeScores() test near the boundaries

w10h01/test/pgdp/trials/TrialOfTheDreamsTest.java
=> [W10H01] Added TrialOfDreams tests

w10h03/test/pgdp/infinite/InfiniteNodeTest.java, w10h03/test/pgdp/infinite/Lambdas.java, w10h03/test/pgdp/infinite/OptimizableLongest.java, w10h03/test/pgdp/infinite/Trees.java
=> [W10H03] Added Tests for heavyTree to see if children are removed properly

w10h02/test/pgdp/teams/Lib.java, w10h02/test/pgdp/teams/UnitTest.java
=> [W10H02] added Test for more Players available than needed Players

w10h01/test/pgdp/trials/TrailOfTheGrassesTest.java, w10h01/test/pgdp/trials/TrialOfTheGrassesTest.java
* Test of the example from `main()`
* Test with a single node
=> [W10H01] Add tests for `TrialOfTheGrasses`

w10h03/test/pgdp/infinite/InfiniteTreeTest.java
Added 3 Tests in InfiniteTreeTest.java to check:
1- Whether the code stops immediately after optimizable.process() return true.
2- Whether the code works correctly after 2 calls without creating a new InfiniteTree.
3- Whether the code exits if from is null.
=> [W10H03] Added tests for amount of calls of next()

w10h02/test/pgdp/teams/UnitTest.java
=> [W10H02] add empty Player Set test

w10h03/test/pgdp/infinite/InfiniteNodeTest.java
- Added a seperate test for the isFullyCalculatedMethod
- Extended the removeChildrenTest for multiple calls
=> [W10H03] Added isFullyCalculatedTest & extended resetChildren

w11h03/test/pgdp/networking/DataHandlerTest.java
=> [W11H03] respond with valid body

w11h03/test/pgdp/networking/NetworkTest.java
=> [W11H03] fix test 12

w11b01/test/pgdp/pengusurvivors/GeneratedGraph.java, w11b01/test/pgdp/pengusurvivors/GraphGenerator.java, w11b01/test/pgdp/pengusurvivors/GraphUtils.java, w11b01/test/pgdp/pengusurvivors/ResidualGraphTest.java
I added basic tests for the first 4 subtasks. Feel free to add more tests and add tests for the last two subtasks.
=> [W11B01] Add tests for first 4 subtasks

w11b01/test/pgdp/pengusurvivors/ResidualGraphTest.java
=> [W11B01] Hotfix

w11b01/test/pgdp/pengusurvivors/GenerateModelTest.java
Simple Test cases testing if max-flow-rate in graph matches maximum number of pengu-paris.
=> [W11B01] GenerateModelTest

w12h03/test/pgdp/shuttle/ShuttleProcessorTests.java
I switch two lines of code, since the task was not executed.
=> [W12H03] ShutDownTest Switched two lines

w12h03/test/pgdp/shuttle/ShuttleProcessorTests.java
=> [W12H03] ShutDownTest Detects now two variants of the Shutdown Message

w13b01/test/pgdp/GameInputStream.java, w13b01/test/pgdp/GameReflectionUtils.java, w13b01/test/pgdp/situationTests/AITest.java, w13b01/test/pgdp/situationTests/CaptureTest.java, w13b01/test/pgdp/situationTests/GeneralTest.java, w13b01/test/pgdp/situationTests/LeaveHomeTest.java, w13b01/test/pgdp/situationTests/ReachGoalTest.java, w13b01/test/pgdp/situationTests/SpecificPinguGame.java, w13b01/test/pgdp/situationTests/TemplateTest.java, w13b01/test/pgdp/situationTests/TestTemplate.java, w13b01/test/pgdp/situationTests/VictoryTest.java
These tests contain checks for specific situations, comparing the outputs to outputs I got from running the tests myself or a example on artemis.
Some situations are created by modifying private members (```boardFields``` and ```figures```) of the ```board``` field in ```PinguGame``` using reflection.
=> [W13B01] added tests for specific situations

w13b01/test/pgdp/game/BasicGameTest.java, w13b01/test/pgdp/game/FiveWholeGames.txt, w13b01/test/pgdp/game/FiveWholeGamesNonStandardSeed.txt, w13b01/test/pgdp/game/HumanPlayerStandardSeed.txt, w13b01/test/pgdp/game/OneWholeGame.txt
A potential issue for wrong solutions: Might get stuck in a loop and produce a relatively large output file, added a Timeout for this reason
=> [W13B01] Added basic human input simulation

w13b01/test/pgdp/GameInputStream.java, w13b01/test/pgdp/game/BasicGameTest.java, w13b01/test/pgdp/game/HumanoidPlayersStandardSeed.txt, w13b01/test/pgdp/situationTests/SpecificPinguGame.java
Fix some brackets + added a Test to simulate 4 human players playing a game
=> [W13B01] HotFix + humanoid tests
